// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package member

import (
	"github.com/google/wire"
	"go-oa/internal/biz"
	"go-oa/internal/server"
)

// Injectors from wire.go:

// InitializeEvent 声明injector的函数签名
func InitializeMember() *Member {
	member := biz.NewMember()
	memberServer := server.NewMemberServer(member)
	memberMember := NewMember(memberServer)
	return memberMember
}

// wire.go:

var BizNewMember = wire.NewSet(biz.NewMember, wire.Bind(new(server.MemberModel), new(*biz.Member)))

var NewMemberServer = wire.NewSet(server.NewMemberServer, wire.Bind(new(MemberServer), new(*server.MemberServer)))
